/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DistributionRouteImport } from './routes/distribution'
import { Route as PackingRouteImport } from './routes/packing'
import { Route as ProcessesRouteImport } from './routes/processes'
import { Route as ReceivingRouteImport } from './routes/receiving'
import { Route as TransportRouteImport } from './routes/transport'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DistributionRoute = DistributionRouteImport.update({
  id: '/distribution',
  path: '/distribution',
  getParentRoute: () => rootRouteImport,
} as any)
const PackingRoute = PackingRouteImport.update({
  id: '/packing',
  path: '/packing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessesRoute = ProcessesRouteImport.update({
  id: '/processes',
  path: '/processes',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceivingRoute = ReceivingRouteImport.update({
  id: '/receiving',
  path: '/receiving',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportRoute = TransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/distribution': typeof DistributionRoute
  '/packing': typeof PackingRoute
  '/processes': typeof ProcessesRoute
  '/receiving': typeof ReceivingRoute
  '/transport': typeof TransportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/distribution': typeof DistributionRoute
  '/packing': typeof PackingRoute
  '/processes': typeof ProcessesRoute
  '/receiving': typeof ReceivingRoute
  '/transport': typeof TransportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/distribution': typeof DistributionRoute
  '/packing': typeof PackingRoute
  '/processes': typeof ProcessesRoute
  '/receiving': typeof ReceivingRoute
  '/transport': typeof TransportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/distribution'
    | '/packing'
    | '/processes'
    | '/receiving'
    | '/transport'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/distribution'
    | '/packing'
    | '/processes'
    | '/receiving'
    | '/transport'
  id:
    | '__root__'
    | '/'
    | '/distribution'
    | '/packing'
    | '/processes'
    | '/receiving'
    | '/transport'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DistributionRoute: typeof DistributionRoute
  PackingRoute: typeof PackingRoute
  ProcessesRoute: typeof ProcessesRoute
  ReceivingRoute: typeof ReceivingRoute
  TransportRoute: typeof TransportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distribution': {
      id: '/distribution'
      path: '/distribution'
      fullPath: '/distribution'
      preLoaderRoute: typeof DistributionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packing': {
      id: '/packing'
      path: '/packing'
      fullPath: '/packing'
      preLoaderRoute: typeof PackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processes': {
      id: '/processes'
      path: '/processes'
      fullPath: '/processes'
      preLoaderRoute: typeof ProcessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receiving': {
      id: '/receiving'
      path: '/receiving'
      fullPath: '/receiving'
      preLoaderRoute: typeof ReceivingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transport': {
      id: '/transport'
      path: '/transport'
      fullPath: '/transport'
      preLoaderRoute: typeof TransportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DistributionRoute: DistributionRoute,
  PackingRoute: PackingRoute,
  ProcessesRoute: ProcessesRoute,
  ReceivingRoute: ReceivingRoute,
  TransportRoute: TransportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
